**PANDAS**


pandas is a python library used working with data sets.it has function for analyzing, cleaning,exploring and manipulating data.pandas allow to us analyzing big make conclusion based on the statistical theories. pandas c an clean meesy data sets,and make them readable and relevent. relevent data us very important in data science. in \pandas 1d is called series, and 2d is called frame and 3d is called panel.

In [ ]:
import pandas as pd
data=[2,3,4,5]
s= pd.Series(data)
print(s)

0    2
1    3
2    4
3    5
dtype: int64

In [ ]:
import pandas as pd
data=(2,3,4,5)
s= pd.Series(data)
print(s)

0    2
1    3
2    4
3    5
dtype: int64

In [ ]:
import pandas as pd
import numpy as np
data=  np.array([[2,6,9,1],[3,4,56,1]])
s=pd.Series(data)
print(s)

ValueError: Data must be 1-dimensional, got ndarray of shape (2, 4) instead

In [ ]:
import pandas as pd
data=[4,5,67,32]
s=pd.Series(data)
print(s)
print(s.shape)
print(s.ndim)
print(s.dtypes)

0     4
1     5
2    67
3    32
dtype: int64
(4,)
1
int64

In [ ]:
import pandas as pd
import numpy as np
data=([4,5,6,7])
s= np.Series(data,index=[100,101,10,20])
print(s)

AttributeError: module 'numpy' has no attribute 'Series'

In [ ]:
import pandas as pd
data={1:'sabitha',3:'misana',8:'sabi'}
s= pd.Series(data)
print(s)

1    sabitha
3     misana
8       sabi
dtype: object

In [ ]:
import numpy as np
import pandas as pd
data={1:'sabitha',8:"misana",3:'sabi'}
s= pd.Series(data,index=[5,1,8,2,3,4])
print(s)
print(s[[3,1]])

5        NaN
1    sabitha
8     misana
2        NaN
3       sabi
4        NaN
dtype: object
3       sabi
1    sabitha
dtype: object

In [ ]:
#data frame
import numpy as np
import pandas as pd
data=[[3,4,5],[2,5,7]]
s= pd.DataFrame(data)
print(s)

   0  1  2
0  3  4  5
1  2  5  7

In [ ]:
import numpy as np
import pandas as pd
data=[['sabitha',30,50,100],['misna',40,50,100]]
s= pd.DataFrame(data)
print(s)

         0   1   2    3
0  sabitha  30  50  100
1    misna  40  50  100

In [5]:

import pandas as pd
import numpy as np

#data [['shinas', 40,60,40]], ['adith',60,30,90], ['sarang', 40,50,12]]

data1 = {'Name': ['shinas', 'adith', 'sarang'], 'chem': [40,60,40], 'maths': [40,60,40], 'phy': [40,60,40]}

df = pd.DataFrame(data1)

df ['bio'] = [60,48,50]

df['total mark'] = df['chem'] + df ['maths'] + df ['phy'] +df['bio']

print(df)

     Name  chem  maths  phy  bio  total mark
0  shinas    40     40   40   60         180
1   adith    60     60   60   48         228
2  sarang    40     40   40   50         170

In [6]:
import pandas as pd
import numpy as np

data1 = {'Name': ['shinas', 'adith', 'sarang'], 'chem': [40,60,40], 'maths': [40,60,40], 'phy': [40,60,40]}
list1 = []

for i in df ['total mark']:
  if i<=100:
     list1.append('blw avg')

  elif i<=200:
     list1.append('avg')

  else:
     list1.append('exlnt')

print(list1)

df['status'] = list1

print(df [['Name', 'status','chem']])

print(df)

['avg', 'exlnt', 'avg']
     Name status  chem
0  shinas    avg    40
1   adith  exlnt    60
2  sarang    avg    40
     Name  chem  maths  phy  bio  total mark status
0  shinas    40     40   40   60         180    avg
1   adith    60     60   60   48         228  exlnt
2  sarang    40     40   40   50         170    avg

In [7]:
import pandas as pd
import numpy as np

data1 = {'Name': ['shinas', 'adith', 'sarang'], 'chem': [40,60,40], 'maths': [40,60,40], 'phy': [40,60,40]}
list1 = []

for i in df ['total mark']:
  if i<=100:
     list1.append('blw avg')

  elif i<=200:
     list1.append('avg')

  else:
     list1.append('exlnt')

print(list1)

del df['chem']

print(df)

['avg', 'exlnt', 'avg']
     Name  maths  phy  bio  total mark status
0  shinas     40   40   60         180    avg
1   adith     60   60   48         228  exlnt
2  sarang     40   40   50         170    avg

In [8]:
import pandas as pd
import numpy as np

data1 = {'Name': ['shinas', 'adith', 'sarang'], 'chem': [40,60,40], 'maths': [40,60,40], 'phy': [40,60,40]}
list1 = []

for i in df ['total mark']:
  if i<=100:
     list1.append('blw avg')

  elif i<=200:
     list1.append('avg')

  else:
     list1.append('exlnt')

print(list1)

df['status'] = list1

print(df)

['avg', 'exlnt', 'avg']
     Name  maths  phy  bio  total mark status
0  shinas     40   40   60         180    avg
1   adith     60   60   48         228  exlnt
2  sarang     40   40   50         170    avg

In [35]:
import pandas as pd

import numpy as np

data1={'name': ['shinas', 'adith', 'sarang'], 'chem': [40,60,40], 'maths': [40,60,40], 'phy': [40,60,46]}

s=pd.DataFrame (data1)


s['bio']=[60,48,50]

s['total']=s['chem']+s['maths']+s['phy']+s['bio']

list1=[]

for i in s['total']:

     if i<=100:
       list1.append('blw avg')
     elif i<=200:
       list1.append('avg')
     else:
      list1.append('exclnt')

#print(list1)

s['status']=list1

print(s)

del s['chem']

s=s.drop('phy', axis=1) #want to specify axis

s.pop('maths')

print(s)

print(s.ndim)

print(s.shape)

print(s.size)
print(s.columns)

print(s['status'].unique())

print(s['bio'].unique())

print(s['status'].value_counts())

print(s)

     name  chem  maths  phy  bio  total  status
0  shinas    40     40   40   60    180     avg
1   adith    60     60   60   48    228  exclnt
2  sarang    40     40   46   50    176     avg
     name  bio  total  status
0  shinas   60    180     avg
1   adith   48    228  exclnt
2  sarang   50    176     avg
2
(3, 4)
12
Index(['name', 'bio', 'total', 'status'], dtype='object')
['avg' 'exclnt']
[60 48 50]
status
avg       2
exclnt    1
Name: count, dtype: int64
     name  bio  total  status
0  shinas   60    180     avg
1   adith   48    228  exclnt
2  sarang   50    176     avg

In [16]:
print(df)

     Name  bio  total mark status
0  shinas   60         180    avg
1   adith   48         228  exlnt
2  sarang   50         170    avg

In [17]:
print(df.head())

     Name  bio  total mark status
0  shinas   60         180    avg
1   adith   48         228  exlnt
2  sarang   50         170    avg

In [18]:
print(df.head(2))

     Name  bio  total mark status
0  shinas   60         180    avg
1   adith   48         228  exlnt

In [19]:
print(df.tail(2))

     Name  bio  total mark status
1   adith   48         228  exlnt
2  sarang   50         170    avg

In [20]:
print(df.describe())

             bio  total mark
count   3.000000    3.000000
mean   52.666667  192.666667
std     6.429101   31.005376
min    48.000000  170.000000
25%    49.000000  175.000000
50%    50.000000  180.000000
75%    55.000000  204.000000
max    60.000000  228.000000

In [21]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      object
 1   bio         3 non-null      int64
 2   total mark  3 non-null      int64
 3   status      3 non-null      object
dtypes: int64(2), object(2)
memory usage: 224.0+ bytes
None

In [28]:
print(df['bio'].sum())

158

In [31]:
print(df.sum(1)) #row wise

TypeError: can only concatenate str (not "int") to str

In [32]:
print(df.sum(0)) #column wise

Name          shinasadithsarang
bio                         158
total mark                  578
status              avgexlntavg
dtype: object

In [33]:
print(df['bio'].mean())

52.666666666666664

In [34]:
print(df.describe())

             bio  total mark
count   3.000000    3.000000
mean   52.666667  192.666667
std     6.429101   31.005376
min    48.000000  170.000000
25%    49.000000  175.000000
50%    50.000000  180.000000
75%    55.000000  204.000000
max    60.000000  228.000000